### ISSUE TITLE
Error when running  docker run

### ISSUE THREAD

**Issue by davidfurlong** [pierreprinetti/certbot#7]
I have no idea what I'm doing, so this may not be an issue with this library

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'future' distribution was not found and is required by parsedatetime
```

**Comment by pierreprinetti** [comment]
The error comes with the default Python that ships with `alpine:3.7`. I have pinned `alpine:3.6`, it will work for now. Just update your certbot image:

```shell
docker pull pierreprinetti/certbot:latest
```
